version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis  # <-- agregado para que Spring sepa dónde está Redis
      SPRING_REDIS_PORT: 6379   # <-- puerto por defecto de Redis
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"


